# Generated by Django 4.0.4 on 2022-05-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_info_address_user_info_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
