# Generated by Django 4.0.4 on 2022-06-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_info_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='profile_pic',
            field=models.ImageField(default='default_avatar.png', upload_to='user_profile_pics'),
        ),
    ]
